version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    hostname: jenkins
    restart: always
    ports:
      - 58080:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home
      - /etc/localtime:/etc/localtime


         
          
