version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql8
    ports:
      - 5306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    volumes:
      - ./db:/var/lib/mysql
      #            - "./conf/my.cnf:/etc/mysql/my.cnf"
      #            - "./init:/docker-entrypoint-initdb.d"
#    adminer: 
#        image: adminer
#        restart: always
#        ports:
#          - 8080:8080
