version: '3'
services:
  nginx:
    image: docker.io/nginx:1.17.3
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./django/app/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/www:/user/share/nginx/html
      - ./django/app:/app

  mongo:
    image: docker.io/mongo:4.0
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    #    command: --replSet qiang
    #   environment:
    #     MONGO_INITDB_ROOT_USERNAME: mongo
    #     MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./mongo/db:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo

  analysis:
    build: ./analysis/
    restart: always
    ports:
      - 5011:5569
    volumes:
      - ./analysis/app:/app
    #command: nohup python main_api.py & \
    #command: /bin/bash ./ 


  django:
    build: ./django/
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./django/app:/app
    #command: gunicorn deltaNLP.wsgi:application -c gunicorn.py 
    #command: bash -c "gunicorn deltaNLP.wsgi:application -c gunicorn.py && while true;  do echo ok; sleep 1; done"



  spider:
    build: ./spider
    restart: always
    ports:
      - 5010:5016
    volumes:
      - ./spider/app:/app
    command: nohup python SpiderMain.py &
         
          
