version: '3'
services:
  mongo:
    image: docker.io/mongo:4.0
    container_name: mongo40
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: agv123
      MONGO_INITDB_ROOT_PASSWORD: agv123
      MONGO_INITDB_DATABASE: AGV-SIM
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime


  nginx:
    image: docker.io/nginx:1.17.2-alpine
    container_name: nginx
    hostname: nginx
    restart: always
    depends_on:
      - mongo
    ports:
      - 8000:8000
      - 8081:8081

    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./roma-ui:/app
      #  - ./nginx/www:/user/share/nginx/html
      - /etc/localtime:/etc/localtime

  simulation:
    build: ./simulation/
    container_name: simulation
    hostname: simulation
    restart: always
    depends_on:
      - algorithm
    ports:
      - 8091:8091
    volumes:
      - /etc/localtime:/etc/localtime
      - ./simulation:/app

  algorithm:
    build: ./algorithm/
    container_name: algorithm
    hostname: algorithm
    restart: always
    depends_on:
      - nginx
    ports:
      - 8085:8085
    volumes:
      - /etc/localtime:/etc/localtime
      - ./algorithm/app:/app


