version: '3'
services:
  mongo:
    image: docker.io/mongo:4.0
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    #    command: --replSet qiang
    #   environment:
    #     MONGO_INITDB_ROOT_USERNAME: mongo
    #     MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./db:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
#      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
