version: '3'
services:
  mongo:
    image: docker.io/mongo:4.0
    container_name: mongo40
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    #   environment:
    #     MONGO_INITDB_ROOT_USERNAME: mongo
    #     MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./mongo/db:/data/db
      - /etc/localtime:/etc/localtime
  #  mongo-express:
  #    image: mongo-express
  #    container_name: mongo-express
  #    restart: always
  #    depends_on:
  #      - mongo
  #    ports:
  #      - 8081:8081
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo

  rabbitmq:
    image: docker.io/rabbitmq:3.6.2-management
    container_name: rabbitmq362
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=roma
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/plugin/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/data:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime
  postgresql:
    image: docker.io/postgres:9.6-alpine
    container_name: postgresql96
    hostname: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456'

    ports:
      - 5432:5432
    volumes:
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime


