version: '3'
services: 
    docker_hub: 
        image: docker.io/registry
        container_name: docker
        hostname: docker
        restart: always
        ports: 
            - 5000:5000
        volumes:
            -  /etc/localtime:/etc/localtime
            - ./docker_registry:/var/lib/registry
            

