version: '3'
networks:
  edgex-network:
    driver: "bridge"

volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  portainer_data:
services:

  volume:
    image: edgexfoundry/docker-edgex-volume:0.6.0
    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data

  consul:
    image: consul:1.1.0
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      edgex-network:
        aliases:
          - edgex-core-consul
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  mongo:
    image: edgexfoundry/docker-edgex-mongo:0.6.0
    ports:
      - "27017:27017"
    container_name: edgex-mongo
    hostname: edgex-mongo
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

        #   mongo:
        #        build: ./
        #       image: mongo
        #       restart: always
        #       ports:
        #         - "27017:27017"
        #       container_name: mongo
        #       networks:
        #           - qiang-network
        #        volumes:
        #            - D:\\WQWorkSpace\\docker\\edgex\\mtbf\\init/:/docker-entrypoint-initdb.d/:ro
        #       environment:
        #           MONGO_INITDB_ROOT_USERNAME: root
        #           MONGO_INITDB_ROOT_PASSWORD: root

        #    mongo-express:
        #        image: mongo-express
        #        restart: always
        #        container_name: mongo-express
        #        networks:
        #            - edgex-network
        #        ports:
        #          - 8081:8081
        #        environment:
        #          ME_CONFIG_MONGODB_ADMINUSERNAME: root
        #          ME_CONFIG_MONGODB_ADMINPASSWORD: root

        #  consul:
        #      image: consul
        #      restart: always
        #      container_name: consul
        #      networks:
        #          - qiang-network
        #      ports:
        #
        #        - "8400:8400"
        #        - "8500:8500"
        #        - "8600:8600"
        #       command: consul agent -data-dir=/tmp/consul -server -bootstrap  -client=0.0.0.0
 
         